### ISSUE TITLE
PyGSTi 0.9.4 install on PyPi is broken

### ISSUE THREAD

**Issue by AdriaanRol** [pyGSTio/pyGSTi#37]
@enielse 
When trying to install PyGSTi using from pypi (https://pypi.python.org/pypi/pyGSTi) using  `pip install pygsti --upgrade` I run into an error because of a missing .pyx file. 
This occurs both on my laptop (screenshot below) as on our online test builds that have PyGSTi as a dependency. 

![screenshot 2018-03-19 15 22 42](https://user-images.githubusercontent.com/6142932/37601075-6cba1426-2b89-11e8-89dd-3136bcefe3b7.png)

**Comment by enielse** [comment]
Thanks for alerting us to this!  I think I've located and fixed the problem in the new 0.9.4.1 release.  The only change in this release is the fix that should allow the PyPi install to work properly on all platforms.  So doing `pip install --upgrade pygsti` should fix this issue.

**Comment by AdriaanRol** [comment]
@enielse I tested your updated pypi version of pygsti. 

Installation seems to work OK however when I try to import it `import pygsti` I get a bunch of import errors (see below). Again, these occur both on our online test builds (that depend on pygsti) and should emulate a linux system as well as on my laptop (mac)

![screenshot 2018-03-20 09 18 51](https://user-images.githubusercontent.com/6142932/37643094-be7bec08-2c1f-11e8-8b3d-0fedcb5105f9.png)

![screenshot 2018-03-20 09 19 00](https://user-images.githubusercontent.com/6142932/37643106-c347a092-2c1f-11e8-9f5c-b87f0b17e58d.png)

**Comment by enielse** [comment]
Ok, we're making progress.  I think I've fixed the `ModuleNotFoundError` in the new version 0.9.4.3 (I had fixed most of the issues in 0.9.4.2 then realized I missed one, hence the 0.9.4.3 - sorry for all the version number shenanigans). Please try `pip install --upgrade pygsti` again and let me know if the import works.

**Comment by AdriaanRol** [comment]
I just tested version 0.9.4.3 from PyPi. It works fine on my laptop but my online builds (e.g., https://travis-ci.org/DiCarloLab-Delft/PycQED_py3/jobs/355364326) are still failing on pygsti. 

It looks like it is because one of the requirements for pygsti (`ply` ) is missing. I checked that pypi lists this as a requirement and that my online build correctly reported 0.9.4.3 .

My guess is that somehow the pip install pygsti does not correctly install the requirements but I'm not sure. 

A temporary workaround could be me adding `ply` to the requirements of our package but that seems a bit hacky.

**Comment by enielse** [comment]
Adriaan - I haven't forgotten about this and even think I may have figured out the problem.  After I do a few more checks I should get a 0.9.4.4 version for you to try, and hopefully that will fix your TravisCI builds.

**Comment by enielse** [comment]
Ok - **version 0.9.4.4** is up.  I've been improving the way we test the pypi distributions, and this one seems to correctly pull in `ply` in all the tests I've run -- let me know if it does for you (fingers crossed).

**Comment by AdriaanRol** [comment]
@enielse I can confirm that the new release solved my problem. Tests are passing again. Thanks!

**Comment by enielse** [comment]
Great - so just to summarize for folks looking at this later on:
- **pip install is broken in pyGSTi 0.9.4** (in various ways; see above posts)
- after 4 minor releases we've been able to get our act together, and **pyGSTi 0.9.4.4** (and later hopefully!) **fixes this issue**.
