### ISSUE TITLE
RB Analysis generated data not consistent 

### ISSUE THREAD

**Issue by newsma** [pyGSTio/pyGSTi#53]
When I tried running "RBAnalysis.ipynb" with "runsims = True", the new RB data that was generated has success counts = 0 for all RB lengths for every iteration. Any ideas why this would be the case? I've attached the "..txt" file for reference.  

[MySimulatedDRBData.txt](https://github.com/pyGSTio/pyGSTi/files/3048412/MySimulatedDRBData.txt)

**Comment by kmrudin** [comment]
Thanks for bringing this to our attention!  I've reproduced this bug (on the latest version of master).  We are looking into this and will get back to you as soon as we have an answer.  Our apologies for the inconvenience!

**Comment by kmrudin** [comment]
The problem was in line 302 of packages/pygsti/extras/rb/simulate.py.  `idealout` is a tuple of ints, not a string; I've fixed this in the develop branch.  Will try to push this to master ASAP, but in the meantime, the other option is to replace the line referenced above:

`scounts.append(outcome.get(idealout,0))`

with

`scounts.append(outcome.get(''.join(str(idealbit) for idealbit in idealout),0))`

**Comment by newsma** [comment]
Thank you for your prompt attention. I cloned the develop brunch and made sure the above-mentioned correction is there (which it is) but I still have the same situation, success counts =0 for all RB lengths for every iteration.

**Comment by kmrudin** [comment]
You're very welcome; sorry this hasn't solved the problem yet!  When I run the RB notebook now I do get non-zero success counts.  Did you restart the Python kernel in the Jupyter notebook (or just start a new Jupyter session) after switching to the develop branch?

**Comment by newsma** [comment]
I indeed started a new kernel but this doesn't seem to fix the issue.

**Comment by kmrudin** [comment]
Hmm... okay, interesting!  Can you tell me what path is returned when you just type in `pygsti` in that Jupyter notebook?  (I'm wondering if you might have multiple installs of pyGSTi and the wrong one (maybe one installed via pip?) is being accessed.)

**Comment by newsma** [comment]
I think you're right. The path is : 

<module 'pygsti' from '/Users/swarnadeepmajumder/miniconda3/lib/python3.7/site-packages/pygsti/__init__.py'>

Is there an easy way to fix this?

**Comment by kmrudin** [comment]
Ah, excellent!

Try the following commands in a terminal session:

```
cd pyGSTi
pip install -e .[complete]
```

**Comment by newsma** [comment]
It works now. Thank you so much for your help. Have a great day!

**Comment by newsma** [comment]
Thank you so much for your help!

Swarnadeep

**Comment by kmrudin** [comment]
Fantastic; glad to be able to help!
